# Generated by Django 6.0.3 on 2026-04-29 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(help_text='Official name of the clinic', max_length=200)),
                ('address', models.TextField(help_text='Full physical address')),
                ('phone', models.CharField(help_text='Primary contact phone number', max_length=50)),
                ('email', models.EmailField(help_text='Primary contact email address', max_length=254)),
                ('working_hours', models.TextField(help_text="Operating hours (e.g., 'Mon-Fri: 8AM-7PM | Sat: 9AM-4PM')")),
                ('logo', models.ImageField(help_text='Clinic logo image', upload_to='branding/')),
                ('facebook_url', models.URLField(blank=True, default='', help_text='Facebook page URL')),
                ('instagram_url', models.URLField(blank=True, default='', help_text='Instagram page URL')),
                ('youtube_url', models.URLField(blank=True, default='', help_text='YouTube channel URL')),
                ('about_text', models.TextField(help_text='About section text describing the clinic')),
                ('about_image', models.ImageField(help_text='Image for the about section', upload_to='about/')),
            ],
            options={
                'verbose_name': 'Clinic Information',
                'verbose_name_plural': 'Clinic Information',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Doctor's full name with title (e.g., 'Dr. James Wilson')", max_length=150)),
                ('specialty', models.CharField(help_text="Medical specialty (e.g., 'Lead Implantologist')", max_length=150)),
                ('bio', models.TextField(help_text='Short biography or description')),
                ('photo', models.ImageField(help_text='Professional photo of the doctor', upload_to='doctors/')),
                ('experience_years', models.PositiveIntegerField(help_text='Years of professional experience')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this doctor is shown on the website')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The FAQ question', max_length=300)),
                ('answer', models.TextField(help_text='The answer to the question')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this FAQ is shown on the website')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gallery image file', upload_to='gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption/description', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this image is shown in the gallery')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text="Main headline text (e.g., 'Your Perfect Smile Starts Here')", max_length=200)),
                ('subheadline', models.TextField(help_text='Subtitle/description text below the headline')),
                ('background_image', models.ImageField(help_text='Background image for the hero section', upload_to='hero/')),
                ('button_text', models.CharField(default='Book Appointment', help_text='Text displayed on the CTA button', max_length=100)),
                ('button_link', models.CharField(default='#', help_text='URL the button links to', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this hero section is currently displayed')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Service name (e.g., 'General Dentistry')", max_length=150)),
                ('description', models.TextField(help_text='Short description of the service')),
                ('icon_image', models.ImageField(blank=True, help_text='Icon image for the service card', null=True, upload_to='services/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this service is shown on the website')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(help_text="Patient's full name", max_length=150)),
                ('review_text', models.TextField(help_text="The patient's review/testimonial text")),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '⭐ (1/5)'), (2, '⭐⭐ (2/5)'), (3, '⭐⭐⭐ (3/5)'), (4, '⭐⭐⭐⭐ (4/5)'), (5, '⭐⭐⭐⭐⭐ (5/5)')], help_text='Star rating (1-5)')),
                ('patient_photo', models.ImageField(blank=True, help_text='Optional patient photo', null=True, upload_to='testimonials/')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this testimonial is shown on the website')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Patient's full name", max_length=150)),
                ('phone', models.CharField(help_text="Patient's phone number", max_length=50)),
                ('email', models.EmailField(help_text="Patient's email address", max_length=254)),
                ('preferred_date', models.DateField(help_text='Requested appointment date')),
                ('preferred_time', models.CharField(help_text='Requested appointment time', max_length=50)),
                ('message', models.TextField(blank=True, default='', help_text='Additional notes from the patient')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When this appointment was submitted')),
                ('is_read', models.BooleanField(default=False, help_text='Whether staff has reviewed this appointment')),
                ('service', models.ForeignKey(blank=True, help_text='Selected dental service', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClinicApp.service')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
