# Generated by Django 6.0.3 on 2026-04-29 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(help_text="Patient's full name as entered in the booking form", max_length=150),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Check this box after you have reviewed the appointment request'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Any additional notes or comments the patient added'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(help_text="Patient's phone number for callback confirmation", max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='preferred_date',
            field=models.DateField(help_text='The date the patient requested for their appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='preferred_time',
            field=models.CharField(help_text="The time the patient requested, e.g. '14:00'", max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, help_text='The dental service the patient selected when booking', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClinicApp.service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Automatically set — the date and time this appointment was submitted'),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='about_image',
            field=models.ImageField(help_text='Image displayed in the About section. Recommended: 800x600px', upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='about_text',
            field=models.TextField(help_text="About section text describing the clinic's history, mission, and values"),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='address',
            field=models.TextField(help_text="Full physical address of the clinic, e.g. '123 Bright Avenue, Suite 200, New York, NY 10001'"),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='clinic_name',
            field=models.CharField(help_text="Official name of the clinic, e.g. 'BrightSmile Dental'", max_length=200),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='email',
            field=models.EmailField(help_text="Primary contact email address, e.g. 'hello@brightsmile.com'", max_length=254),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='facebook_url',
            field=models.URLField(blank=True, default='', help_text="Full URL to the clinic's Facebook page. Leave empty to hide the Facebook link."),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='instagram_url',
            field=models.URLField(blank=True, default='', help_text="Full URL to the clinic's Instagram page. Leave empty to hide the Instagram link."),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='logo',
            field=models.ImageField(help_text='Clinic logo image displayed in the navigation bar and footer. Recommended: transparent PNG, 200x60px', upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='phone',
            field=models.CharField(help_text="Primary contact phone number, e.g. '(555) 123-4567'", max_length=50),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='working_hours',
            field=models.TextField(help_text="Operating hours, e.g. 'Mon–Fri: 8AM–7PM | Sat: 9AM–4PM'"),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='youtube_url',
            field=models.URLField(blank=True, default='', help_text="Full URL to the clinic's YouTube channel. Leave empty to hide the YouTube link."),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(help_text="Short biography or description shown below the doctor's name"),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveIntegerField(help_text='Number of years of professional experience, e.g. 7'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(help_text="Doctor's full name with title, e.g. 'Dr. James Wilson'", max_length=150),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this doctor from the website without deleting the record'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order — lower numbers appear first on the website (e.g. 1, 2, 3)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(help_text='Professional headshot photo of the doctor. Recommended: square image, at least 300x300px', upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(help_text="Medical specialty, e.g. 'Lead Implantologist' or 'Orthodontics Specialist'", max_length=150),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(help_text='The detailed answer to the question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this FAQ from the website without deleting it'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order — lower numbers appear first on the website (e.g. 1, 2, 3)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(help_text="The FAQ question text, e.g. 'Do you accept dental insurance?'", max_length=300),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(blank=True, help_text="Optional caption describing the image, e.g. 'Before & After: Teeth Whitening'", max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='Gallery image file. Recommended: landscape orientation, at least 600x400px', upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this image from the gallery without deleting it'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order — lower numbers appear first in the gallery grid (e.g. 1, 2, 3)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(help_text='Background image for the hero section. Recommended size: 1200x800px', upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_link',
            field=models.CharField(default='#', help_text="URL the button links to. Leave as '#' to open the booking modal", max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_text',
            field=models.CharField(default='Book Appointment', help_text="Text displayed on the call-to-action button, e.g. 'Book Appointment'", max_length=100),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='headline',
            field=models.CharField(help_text="Main headline text shown at the top of the homepage, e.g. 'Your Perfect Smile Starts Here'", max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check to display this hero section on the website. Uncheck to hide it.'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subheadline',
            field=models.TextField(help_text='Subtitle or description text displayed below the main headline'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Short description of the service shown on the service card'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Icon image for the service card. If left empty, a default tooth icon is shown.', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this service from the website without deleting it'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order — lower numbers appear first on the website (e.g. 1, 2, 3)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(help_text="Service name as it appears on the website, e.g. 'General Dentistry'", max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this testimonial from the website without deleting it'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='patient_name',
            field=models.CharField(help_text="Patient's full name as shown in the review", max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='patient_photo',
            field=models.ImageField(blank=True, help_text='Optional photo of the patient. Leave empty if the patient prefers anonymity.', null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '⭐ (1/5)'), (2, '⭐⭐ (2/5)'), (3, '⭐⭐⭐ (3/5)'), (4, '⭐⭐⭐⭐ (4/5)'), (5, '⭐⭐⭐⭐⭐ (5/5)')], help_text='Star rating from 1 to 5 stars given by the patient'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='review_text',
            field=models.TextField(help_text="The patient's testimonial or review text"),
        ),
    ]
