# Generated by Django 6.0.3 on 2026-04-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0002_alter_appointment_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, default='', help_text="Patient's email address (optional)", max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='preferred_time',
            field=models.CharField(blank=True, default='', help_text="The time the patient requested, e.g. '14:00' (optional)", max_length=50),
        ),
    ]
