# Generated by Django 5.2.13 on 2026-05-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0003_alter_appointment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicinfo',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', help_text="Telegram Bot Token from @BotFather, e.g. '123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11'", max_length=200),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text="Telegram Group/Channel ID where notifications are sent, e.g. '-1001234567890'", max_length=100),
        ),
    ]
