# Generated by Django 5.2.13 on 2026-05-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0004_clinicinfo_telegram_bot_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='background_image',
        ),
    ]
