# Generated by Django 5.2.13 on 2026-05-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0005_remove_herosection_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicinfo',
            name='about_text_en',
            field=models.TextField(help_text="About section text describing the clinic's history, mission, and values", null=True),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='about_text_ru',
            field=models.TextField(help_text="About section text describing the clinic's history, mission, and values", null=True),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='about_text_uz',
            field=models.TextField(help_text="About section text describing the clinic's history, mission, and values", null=True),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='address_en',
            field=models.TextField(help_text="Full physical address of the clinic, e.g. '123 Bright Avenue, Suite 200, New York, NY 10001'", null=True),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='address_ru',
            field=models.TextField(help_text="Full physical address of the clinic, e.g. '123 Bright Avenue, Suite 200, New York, NY 10001'", null=True),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='address_uz',
            field=models.TextField(help_text="Full physical address of the clinic, e.g. '123 Bright Avenue, Suite 200, New York, NY 10001'", null=True),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='clinic_name_en',
            field=models.CharField(help_text="Official name of the clinic, e.g. 'BrightSmile Dental'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='clinic_name_ru',
            field=models.CharField(help_text="Official name of the clinic, e.g. 'BrightSmile Dental'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='clinic_name_uz',
            field=models.CharField(help_text="Official name of the clinic, e.g. 'BrightSmile Dental'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='working_hours_en',
            field=models.TextField(help_text="Operating hours, e.g. 'Mon–Fri: 8AM–7PM | Sat: 9AM–4PM'", null=True),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='working_hours_ru',
            field=models.TextField(help_text="Operating hours, e.g. 'Mon–Fri: 8AM–7PM | Sat: 9AM–4PM'", null=True),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='working_hours_uz',
            field=models.TextField(help_text="Operating hours, e.g. 'Mon–Fri: 8AM–7PM | Sat: 9AM–4PM'", null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio_en',
            field=models.TextField(help_text="Short biography or description shown below the doctor's name", null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio_ru',
            field=models.TextField(help_text="Short biography or description shown below the doctor's name", null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio_uz',
            field=models.TextField(help_text="Short biography or description shown below the doctor's name", null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_name_en',
            field=models.CharField(help_text="Doctor's full name with title, e.g. 'Dr. James Wilson'", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_name_ru',
            field=models.CharField(help_text="Doctor's full name with title, e.g. 'Dr. James Wilson'", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_name_uz',
            field=models.CharField(help_text="Doctor's full name with title, e.g. 'Dr. James Wilson'", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_en',
            field=models.CharField(help_text="Medical specialty, e.g. 'Lead Implantologist' or 'Orthodontics Specialist'", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_ru',
            field=models.CharField(help_text="Medical specialty, e.g. 'Lead Implantologist' or 'Orthodontics Specialist'", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_uz',
            field=models.CharField(help_text="Medical specialty, e.g. 'Lead Implantologist' or 'Orthodontics Specialist'", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(help_text='The detailed answer to the question', null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(help_text='The detailed answer to the question', null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(help_text='The detailed answer to the question', null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(help_text="The FAQ question text, e.g. 'Do you accept dental insurance?'", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(help_text="The FAQ question text, e.g. 'Do you accept dental insurance?'", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(help_text="The FAQ question text, e.g. 'Do you accept dental insurance?'", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption_en',
            field=models.CharField(blank=True, help_text="Optional caption describing the image, e.g. 'Before & After: Teeth Whitening'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption_ru',
            field=models.CharField(blank=True, help_text="Optional caption describing the image, e.g. 'Before & After: Teeth Whitening'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption_uz',
            field=models.CharField(blank=True, help_text="Optional caption describing the image, e.g. 'Before & After: Teeth Whitening'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_text_en',
            field=models.CharField(default='Book Appointment', help_text="Text displayed on the call-to-action button, e.g. 'Book Appointment'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_text_ru',
            field=models.CharField(default='Book Appointment', help_text="Text displayed on the call-to-action button, e.g. 'Book Appointment'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_text_uz',
            field=models.CharField(default='Book Appointment', help_text="Text displayed on the call-to-action button, e.g. 'Book Appointment'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='headline_en',
            field=models.CharField(help_text="Main headline text shown at the top of the homepage, e.g. 'Your Perfect Smile Starts Here'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='headline_ru',
            field=models.CharField(help_text="Main headline text shown at the top of the homepage, e.g. 'Your Perfect Smile Starts Here'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='headline_uz',
            field=models.CharField(help_text="Main headline text shown at the top of the homepage, e.g. 'Your Perfect Smile Starts Here'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subheadline_en',
            field=models.TextField(help_text='Subtitle or description text displayed below the main headline', null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subheadline_ru',
            field=models.TextField(help_text='Subtitle or description text displayed below the main headline', null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subheadline_uz',
            field=models.TextField(help_text='Subtitle or description text displayed below the main headline', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(help_text='Short description of the service shown on the service card', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(help_text='Short description of the service shown on the service card', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_uz',
            field=models.TextField(help_text='Short description of the service shown on the service card', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(help_text="Service name as it appears on the website, e.g. 'General Dentistry'", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(help_text="Service name as it appears on the website, e.g. 'General Dentistry'", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_uz',
            field=models.CharField(help_text="Service name as it appears on the website, e.g. 'General Dentistry'", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='patient_name_en',
            field=models.CharField(help_text="Patient's full name as shown in the review", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='patient_name_ru',
            field=models.CharField(help_text="Patient's full name as shown in the review", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='patient_name_uz',
            field=models.CharField(help_text="Patient's full name as shown in the review", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='review_text_en',
            field=models.TextField(help_text="The patient's testimonial or review text", null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='review_text_ru',
            field=models.TextField(help_text="The patient's testimonial or review text", null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='review_text_uz',
            field=models.TextField(help_text="The patient's testimonial or review text", null=True),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Image displayed in the About section. Recommended: 800x600px. Leave empty for gradient placeholder.', null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='clinicinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Clinic logo image displayed in the navigation bar and footer. Recommended: transparent PNG, 200x60px. Leave empty for text-based logo.', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Professional headshot photo of the doctor. Recommended: square image, at least 300x300px. Leave empty for default avatar.', null=True, upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Gallery image file. Recommended: landscape orientation, at least 600x400px. Leave empty for placeholder.', null=True, upload_to='gallery/'),
        ),
    ]
