# Generated by Django 5.2.13 on 2026-05-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0007_remove_clinicinfo_about_text_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.RemoveField(
            model_name='clinicinfo',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='clinicinfo',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='clinicinfo',
            name='telegram_bot_token',
        ),
        migrations.RemoveField(
            model_name='clinicinfo',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='clinicinfo',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='telegram_url',
            field=models.URLField(blank=True, default='', help_text="Full URL to the clinic's Telegram channel. Leave empty to hide the Telegram link."),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, help_text="Short biography or description shown below the doctor's name (optional)", null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Display order — lower numbers appear first on the website (e.g. 1, 2, 3) (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the service shown on the service card (optional)', null=True),
        ),
    ]
