# Generated by Django 5.2.13 on 2026-05-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0008_delete_faq_remove_clinicinfo_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicinfo',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', help_text="Telegram Bot Token from @BotFather, e.g. '123456789:ABCdefGHIjklMNOpqrsTUVwxyz'", max_length=200),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='Your personal Telegram Chat ID to receive appointment notifications. Get it from @userinfobot', max_length=50),
        ),
    ]
