# Generated by Django 5.2.13 on 2026-05-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0009_clinicinfo_telegram_bot_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='preferred_date',
            field=models.DateField(blank=True, help_text='The date the patient requested for their appointment (optional)', null=True),
        ),
    ]
