# Generated by Django 5.2.13 on 2026-05-07 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0010_alter_appointment_preferred_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
    ]
